/*
 * ultrasonic.c
 *
 *  Created on: Oct 16, 2024
 *      Author: aisha
 */


#include "ultrasonic.h"
#include "icu.h"
#include "gpio.h"
#include <util/delay.h>

/*******************************************************************************
 *                           Global Variables                                  *
 *******************************************************************************/

uint8 g_edgeCount = 0;
uint16 g_timeHigh = 0;

/*******************************************************************************
 *                      Functions Definitions                                   *
 *******************************************************************************/

/*
 * Description :
 * Function to Initialize the Ultrasonic sensor
 * Input: void
 * Output: void
 */
void Ultrasonic_init(void)
{
	/* Initializing the ICU */
	ICU_ConfigType config = {F_CPU_8, RAISING_EDGE};
	ICU_init(&config);
	ICU_setCallBack(Ultrasonic_edgeProcessing);

	/* Setting the Trigger pin as o/p */
	GPIO_setupPinDirection(ULTRASONIC_TRIG_PORTID, ULTRASONIC_TRIG_PINID, PIN_OUTPUT);
}

/*
 * Description :
 * Function to Send the trigger pulse to the ultrasonic sensor.
 * Input: void
 * Output: void
 */
void Ultrasonic_Trigger(void)
{
	/* Set Trigger Pin */
	GPIO_writePin(ULTRASONIC_TRIG_PORTID, ULTRASONIC_TRIG_PINID, LOGIC_HIGH);

	/* Delay for 15us */
	_delay_us(15);

	/* Clear Trigger Pin */
	GPIO_writePin(ULTRASONIC_TRIG_PORTID, ULTRASONIC_TRIG_PINID, LOGIC_LOW);
}

/*
 * Description :
 * Function to Calculate The measured distance in centimeters.
 * Input: void
 * Output: void
 */
uint16 Ultrasonic_readDistance(void)
{
	/* Send the trigger pulse */
	Ultrasonic_Trigger();

	/* Waiting for the echo to receive the pulse */
	while(g_edgeCount != 2);
	g_edgeCount = 0;

	/* Calculate the distance */
	g_timeHigh = (uint16)((float)(g_timeHigh) / 117.6) + 1;

	return g_timeHigh;
}

/*
 * Description :
 * Function to calculate the high time (pulse time) generated by the ultrasonic sensor.
 * Input: void
 * Output: void
 */
void Ultrasonic_edgeProcessing(void)
{
	++g_edgeCount;
	if(g_edgeCount == 1)
	{
		/*
		 * Clear the timer counter register to start measurements from the
		 * first detected rising edge
		 */
		ICU_clearTimerValue();

		/* Detect falling edge */
		ICU_setEdgeDetectionType(FALLING_EDGE);
	}
	else if(g_edgeCount == 2)
	{
		/* Store the High time value */
		g_timeHigh = ICU_getInputCaptureValue();

		/* Detect rising edge */
		ICU_setEdgeDetectionType(RAISING_EDGE);
	}
}
